# GitHub Actions CI/CD Pipeline for MuzikaPlayer
name: MuzikaPlayer CI/CD

on:
  push:
    branches:
      - main
    paths:
      - 'MuzikaPlayer/**'
      - '.github/workflows/muzikaplayer-deploy.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'MuzikaPlayer/**'
      - '.github/workflows/muzikaplayer-deploy.yaml'
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: true
        default: 'staging'
        type: choice
        options:
          - staging
          - production
      skip_build:
        description: 'Skip build step'
        required: false
        default: false
        type: boolean

env:
  ACR_NAME: ${{ secrets.ACR_NAME }}
  AKS_CLUSTER_NAME: ${{ secrets.AKS_CLUSTER_NAME }}
  AKS_RESOURCE_GROUP: ${{ secrets.AKS_RESOURCE_GROUP }}
  IMAGE_NAME: muzika/muzikaplayer

jobs:
  build:
    name: Build Frontend
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.version.outputs.image_tag }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: MuzikaPlayer/package-lock.json

      - name: Generate version
        id: version
        run: |
          SHORT_SHA=$(git rev-parse --short HEAD)
          IMAGE_TAG="latest-${SHORT_SHA}"
          echo "image_tag=${IMAGE_TAG}" >> $GITHUB_OUTPUT

      - name: Install dependencies
        working-directory: MuzikaPlayer
        run: npm ci

      - name: Build application
        if: ${{ github.event.inputs.skip_build != 'true' }}
        working-directory: MuzikaPlayer
        run: npm run build

      - name: Verify build output
        working-directory: MuzikaPlayer
        run: |
          if [ ! -d "dist" ] || [ -z "$(ls -A dist)" ]; then
            echo "ERROR: dist folder is empty or does not exist"
            exit 1
          fi
          echo "✓ Build output verified"
          ls -la dist/

  docker:
    name: Build & Push Docker Image
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Validate ACR configuration
        run: |
          [ -n "${{ secrets.ACR_NAME }}" ] || (echo "ERROR: ACR_NAME secret is not set" && exit 1)
          [ -n "${{ secrets.ACR_USERNAME }}" ] || (echo "ERROR: ACR_USERNAME secret is not set" && exit 1)
          [ -n "${{ secrets.ACR_PASSWORD }}" ] || (echo "ERROR: ACR_PASSWORD secret is not set" && exit 1)

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.ACR_NAME }}.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./MuzikaPlayer
          push: true
          tags: |
            ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ needs.build.outputs.image_tag }}
            ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:buildcache
          cache-to: type=registry,ref=${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:buildcache,mode=max

      - name: Output image details
        run: |
          echo "### Docker Image Built" >> $GITHUB_STEP_SUMMARY
          echo "- **Registry:** ${{ secrets.ACR_NAME }}.azurecr.io" >> $GITHUB_STEP_SUMMARY
          echo "- **Image:** ${{ env.IMAGE_NAME }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Tag:** ${{ needs.build.outputs.image_tag }}" >> $GITHUB_STEP_SUMMARY

  deploy:
    name: Deploy to AKS
    runs-on: ubuntu-latest
    needs: [build, docker]
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    environment: 
      name: ${{ github.event.inputs.environment || 'staging' }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure Kubernetes context
        id: kubeconfig-setup
        continue-on-error: true
        run: |
          if [ -n "${{ secrets.KUBE_CONFIG_BASE64 }}" ]; then
            mkdir -p ${HOME}/.kube
            echo "${{ secrets.KUBE_CONFIG_BASE64 }}" | base64 --decode > ${HOME}/.kube/config
            chmod 600 ${HOME}/.kube/config
            echo "kubeconfig_used=true" >> $GITHUB_OUTPUT
          else
            echo "kubeconfig_used=false" >> $GITHUB_OUTPUT
          fi

      - name: Azure Login
        if: steps.kubeconfig-setup.outputs.kubeconfig_used != 'true'
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Set AKS context
        if: steps.kubeconfig-setup.outputs.kubeconfig_used != 'true'
        uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ env.AKS_RESOURCE_GROUP }}
          cluster-name: ${{ env.AKS_CLUSTER_NAME }}

      - name: Install kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Create namespace
        run: |
          kubectl create namespace muzika --dry-run=client -o yaml | kubectl apply -f -

      - name: Update manifests
        run: |
          cd MuzikaPlayer/k8s
          sed -i "s/newTag: .*/newTag: ${{ needs.build.outputs.image_tag }}/" kustomization.yaml
          sed -i "s/\${ACR_NAME}/${{ secrets.ACR_NAME }}/g" deployment.yaml kustomization.yaml

      - name: Deploy MuzikaPlayer
        run: |
          cd MuzikaPlayer/k8s
          kubectl apply -k .
          kubectl rollout status deployment/muzikaplayer -n muzika --timeout=300s

      - name: Update Ingress
        run: |
          kubectl apply -f ${{ github.workspace }}/ingress.yaml

      - name: Verify deployment
        run: |
          echo "### Deployment Status" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          kubectl get pods -n muzika -l app=muzikaplayer >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "### Service Status" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          kubectl get svc -n muzika muzikaplayer >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

      - name: Cleanup on failure
        if: failure()
        run: |
          kubectl logs -n muzika -l app=muzikaplayer --tail=50 || true
          kubectl describe pods -n muzika -l app=muzikaplayer || true

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: [build, docker, deploy]
    if: always()
    
    steps:
      - name: Create deployment summary
        run: |
          echo "## Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "| Job | Status |" >> $GITHUB_STEP_SUMMARY
          echo "|-----|--------|" >> $GITHUB_STEP_SUMMARY
          echo "| Build | ${{ needs.build.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Docker | ${{ needs.docker.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "| Deploy | ${{ needs.deploy.result }} |" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Image Tag:** ${{ needs.build.outputs.image_tag }}" >> $GITHUB_STEP_SUMMARY
          echo "**Commit:** ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
